# Generated by create-filler (simple-jit vertical). Copy to `.env` and fill in.

# === REQUIRED — solver identity ===

# Solver wallet private key — 0x-prefixed 32-byte hex.
# Anvil dev account #0 (BURN-IT, never send real funds):
#   0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
SOLVER_PRIVATE_KEY=

# === REQUIRED — network ===

# Chain id (you scaffolded for `{{chain}}`).
# Supported: 1 mainnet | 130 unichain | 8453 base | 42161 arbitrum | 10 optimism
#            11155111 sepolia | 11155420 unichain-sepolia | 31337 foundry
CHAIN_ID=

# RPC endpoint — must be https:// (http:// only allowed for localhost).
RPC_URL={{rpcUrl}}

# Optional WebSocket RPC for live event subscription (wss://).
# WS_RPC_URL=

# === REQUIRED — deployed contract addresses ===

# Your `Filler.sol` deployment (the trusted intermediary that calls the Reactor).
FILLER_ADDRESS=

# Your `FillerBond.sol` deployment (slashable bond pool that backs fills).
BOND_ADDRESS=

# UniswapX V2DutchOrderReactor address for {{chain}}.
REACTOR_ADDRESS=

# Uniswap v4 PoolManager address for {{chain}}.
POOL_MANAGER_ADDRESS=

# === OPTIONAL ===

# JIT-hints indexer URL.
# Self-host via the @filler-sdk/jit-hints package for private depth queries.
INDEXER_URL={{indexerUrl}}

# Minimum profit per fill in USD (denominated in output token's smallest unit
# at 6-decimal USDC convention). Fills below this threshold are skipped.
MIN_PROFIT_USD=1

# Logging level: trace | debug | info | warn | error | fatal
LOG_LEVEL=info{{#if useKeeperHub}}

# === KeeperHub (MEV-protected routing) ===

# Bearer token from KeeperHub onboarding.
KEEPERHUB_API_KEY=

# KeeperHub HTTP API base URL.
KEEPERHUB_BASE_URL=https://api.keeperhub.example.com{{/if}}
