# {{projectName}}

Simple JIT Filler — UniswapX vertical solver on `{{chain}}`. Generated by `create-filler` ({{currentYear}}).

> *"Tres archivos y un bond."*

## Quickstart

```bash
# 1. Configure
cp .env.example .env
# Edit .env — set SOLVER_PRIVATE_KEY, RPC_URL, CHAIN_ID, and the four contract addresses.

# 2. Install
bun install

# 3. Stake bond (one-time, before first fill).
#    Default 0.1 ETH. Pass a wei amount to override:
bun stake                    # 0.1 ETH
bun stake 1000000000000000000  # 1 ETH

# 4. Run the solver
bun start
```

## Architecture (three files + one bond)

```
src/
├── config.ts     # Zod-validated environment loader
├── strategy.ts   # filter() + decide() — your customisation point
├── filler.ts     # Main loop (subscribe → prepare → submit)
└── stake.ts      # One-time bond setup helper
```

The bond contract is `FillerBond.sol`, deployed at `BOND_ADDRESS` from your `.env`. It backs every fill — if the Reactor's slash path fires, your stake decrements.

## Environment variables

| Variable               | Description                                                  | Required          |
| ---------------------- | ------------------------------------------------------------ | ----------------- |
| `SOLVER_PRIVATE_KEY`   | 0x-prefixed 32-byte hex                                      | ✅                |
| `CHAIN_ID`             | One of 1 / 130 / 8453 / 42161 / 10 / 11155111 / 11155420 / 31337 | ✅            |
| `RPC_URL`              | https:// RPC endpoint                                        | ✅                |
| `WS_RPC_URL`           | wss:// for live events (recommended)                         | optional          |
| `FILLER_ADDRESS`       | Your `Filler.sol` deployment                                 | ✅                |
| `BOND_ADDRESS`         | Your `FillerBond.sol` deployment                             | ✅                |
| `REACTOR_ADDRESS`      | UniswapX V2 Reactor for the chain                            | ✅                |
| `POOL_MANAGER_ADDRESS` | Uniswap v4 PoolManager for the chain                         | ✅                |
| `INDEXER_URL`          | JIT-hints indexer (default `{{indexerUrl}}`)                 | optional          |
| `MIN_PROFIT_USD`       | Skip fills below this. Default 1.                            | optional          |
| `LOG_LEVEL`            | `trace`/`debug`/`info`/`warn`/`error`. Default `info`.       | optional          |{{#if useKeeperHub}}
| `KEEPERHUB_API_KEY`    | Bearer token (MEV-protected routing via KeeperHub)           | ✅ (when KH on)   |
| `KEEPERHUB_BASE_URL`   | KeeperHub HTTP API URL                                       | ✅ (when KH on)   |{{/if}}

## Customising

Edit `src/strategy.ts`:

```ts
filter(intent: Intent): boolean {
  // Allowlist input tokens, blocklist swappers, dust-filter, etc.
  return ALLOWED_TOKENS.has(intent.input.token.toLowerCase());
}

decide(intent: Intent, params: FillParams, minProfitWei: bigint): boolean {
  // Override the default "feesCaptured >= minProfitWei" — e.g. compare
  // against gas estimate, oracle mid-price, or time-of-day.
  return params.feesCaptured >= minProfitWei * 2n; // require 2× threshold
}
```

The rest of `src/` doesn't need to change. The `Filler` SDK handles intent decoding, depth queries, tick calibration, simulation, broadcast, retries, and (optionally) KeeperHub-protected routing.

## Deployment

This template generates a project meant to run on a Linux server (or
container). For production:

1. Set `LOG_LEVEL=info` and pipe stdout into your aggregator (Datadog / Loki / etc.) — the SDK emits structured JSON.
2. Run under a process supervisor (systemd / pm2 / Docker restart) so a crash auto-restarts.
3. Monitor `feeCapturedAmount` via the `✓ fill submitted` log line. Alert on a sustained drop.
4. Hold spare ETH in `SOLVER_PRIVATE_KEY` for gas — the SDK doesn't refill itself.

## Troubleshooting

| Symptom                                         | Likely cause                                                 |
| ----------------------------------------------- | ------------------------------------------------------------ |
| `[{{projectName}}] invalid configuration`       | Missing / malformed env var. Check `.env.example` for shape. |
| `prepareFill threw` repeatedly                  | Indexer down or wrong `INDEXER_URL`.                         |
| `✗ fill failed: BroadcastFailedError`           | Tx mined but reverted. Check the `txHash` on Etherscan.      |
| `✗ fill failed: TimeoutError`                   | Receipt didn't arrive in 60s. Mempool congestion or RPC slow.|
| Fills land but `feeCapturedAmount` is 0         | Indexer's hint over-promised; check pool depth.              |

## Documentation

- [Filler SDK reference](https://docs.filler-sdk.xyz)
- [JIT-hints indexer](https://github.com/filler-sdk/filler-sdk/tree/main/packages/jit-hints)
- [Sprint 04 plans](https://github.com/filler-sdk/filler-sdk/tree/main/plans/sprint-04-cli-references)

## License

MIT
