import { describe, expect, test } from 'vitest';

import {
  MAX_SQRT_PRICE,
  MAX_TICK,
  MIN_SQRT_PRICE,
  MIN_TICK,
  getSqrtRatioAtTick,
  getTickAtSqrtRatio,
} from '../../src/depth/tickMath';

import vectorsJson from '../fixtures/tickMathVectors.json' with { type: 'json' };

interface Vector {
  tick: number;
  sqrtPriceX96: string;
}

const vectors: Vector[] = vectorsJson as Vector[];

/**
 * Cross-check the TS TickMath port against fixtures generated by `forge script
 * GenerateTickMathVectors.s.sol`. Each fixture is a `(tick, sqrtPriceX96)` pair
 * produced by v4-core's Solidity TickMath. The TS port must agree EXACTLY for
 * every sampled tick — divergence here means the off-chain solver math drifts
 * from on-chain reality.
 */
describe('TickMath fixture cross-check (Plan 04 audit)', () => {
  test(`fixture file is non-empty (${vectors.length} vectors)`, () => {
    expect(vectors.length).toBeGreaterThan(50);
    // Spot the edges so a malformed fixture can't pass silently.
    expect(vectors[0]?.tick).toBe(MIN_TICK);
    expect(vectors.find((v) => v.tick === MAX_TICK)).toBeDefined();
  });

  test('every tick in fixtures is within [MIN_TICK, MAX_TICK]', () => {
    for (const v of vectors) {
      expect(v.tick).toBeGreaterThanOrEqual(MIN_TICK);
      expect(v.tick).toBeLessThanOrEqual(MAX_TICK);
    }
  });

  test.each(vectors)(
    'getSqrtRatioAtTick($tick) matches v4-core',
    ({ tick, sqrtPriceX96 }: Vector) => {
      const expected = BigInt(sqrtPriceX96);
      const actual = getSqrtRatioAtTick(tick);
      expect(actual).toBe(expected);
    },
  );

  test.each(vectors)(
    'getTickAtSqrtRatio of v4-core sqrtPrice($tick) round-trips',
    ({ tick, sqrtPriceX96 }: Vector) => {
      const sqrt = BigInt(sqrtPriceX96);
      // The MAX_TICK fixture's sqrtPrice IS MAX_SQRT_PRICE itself, which
      // `getTickAtSqrtRatio` rejects (the function is strict-less-than on the
      // upper bound). Skip that single case — the corresponding tick is
      // unreachable through getTickAtSqrtRatio by design.
      if (sqrt >= MAX_SQRT_PRICE) {
        expect(sqrt).toBe(MAX_SQRT_PRICE);
        return;
      }
      // The MIN_SQRT_PRICE corresponds to MIN_TICK; we DO accept it and expect
      // round-trip identity.
      if (sqrt < MIN_SQRT_PRICE) {
        // Should not happen by construction — the fixture is from getSqrtRatioAtTick.
        throw new Error(`fixture sqrtPriceX96 ${sqrt} below MIN_SQRT_PRICE`);
      }
      expect(getTickAtSqrtRatio(sqrt)).toBe(tick);
    },
  );

  test('sqrtPrice values are strictly monotone in tick (deduped)', () => {
    // The script's sampling produces a couple of incidental duplicates (e.g.,
    // tick=1 lands in both the dense-around-zero bucket and the powers-of-two
    // bucket). Dedup before asserting strict monotonicity.
    const byTick = new Map<number, bigint>();
    for (const v of vectors) byTick.set(v.tick, BigInt(v.sqrtPriceX96));
    const sorted = [...byTick.entries()].sort((a, b) => a[0] - b[0]);
    for (let i = 1; i < sorted.length; i++) {
      expect(sorted[i]![1]).toBeGreaterThan(sorted[i - 1]![1]);
    }
  });

  test('the MIN_TICK and MAX_TICK fixtures match the on-chain bounds exactly', () => {
    const minVec = vectors.find((v) => v.tick === MIN_TICK);
    const maxVec = vectors.find((v) => v.tick === MAX_TICK);
    expect(BigInt(minVec!.sqrtPriceX96)).toBe(MIN_SQRT_PRICE);
    expect(BigInt(maxVec!.sqrtPriceX96)).toBe(MAX_SQRT_PRICE);
  });
});
