# Generated by create-filler (lvr-aware vertical). Copy to `.env` and fill in.

# === REQUIRED — solver identity ===

SOLVER_PRIVATE_KEY=

# === REQUIRED — network ===

# Chain id (you scaffolded for `{{chain}}`).
# Supported: 1 mainnet | 130 unichain | 8453 base | 42161 arbitrum | 10 optimism
#            11155111 sepolia | 11155420 unichain-sepolia | 31337 foundry
CHAIN_ID=

# RPC endpoint — must be https:// (http:// only allowed for localhost).
RPC_URL={{rpcUrl}}

# Optional WebSocket RPC for live event subscription (wss://).
# WS_RPC_URL=

# === REQUIRED — deployed contract addresses ===

FILLER_ADDRESS=
BOND_ADDRESS=
REACTOR_ADDRESS=
POOL_MANAGER_ADDRESS=

# === OPTIONAL — indexer + strategy ===

INDEXER_URL={{indexerUrl}}

# Minimum NET profit per fill (USD). LVR-aware computes net AFTER intended
# donation (DONATION_BPS), so set this to your absolute floor — sub-threshold
# fills are skipped entirely.
MIN_PROFIT_USD=1

# === LVR-aware tunables ===

# Implied volatility in bps. 200 = 2% annualised. v0 is a static value; v1
# replaces with an oracle (Pyth realised-vol or similar).
VOLATILITY_BPS=200

# Pool liquidity proxy (wei). Larger = smaller estimated LVR per fill.
# Fetch from your indexer's pool snapshot or hard-code per pool.
BASE_LIQUIDITY_HINT=1000000000000000000

# Fraction of fees we'd donate back to LPs (bps; 2500 = 25%). v0 metric-only;
# the on-chain donate path requires Filler.sol extension (see README).
DONATION_BPS=2500

# === Observability ===

LOG_LEVEL=info

# Prometheus metrics port. /metrics + /health endpoints.
METRICS_PORT=9090{{#if useKeeperHub}}

# === KeeperHub (MEV-protected routing) ===

KEEPERHUB_API_KEY=
KEEPERHUB_BASE_URL=https://api.keeperhub.example.com{{/if}}
