# {{projectName}} — LVR-Aware Filler

Vertical solver on `{{chain}}` that prioritizes LP-favourable fills. Generated by `create-filler` ({{currentYear}}).

> *Filling fewer intents, but the right ones.*

## When to use this vs simple-jit?

| Goal                                    | Use this vertical |
| --------------------------------------- | ----------------- |
| Maximise solver fee per fill            | `simple-jit`      |
| Optimise for **pool sustainability**    | `lvr-aware` ✓     |
| Build a relationship with LP-DAOs       | `lvr-aware` ✓     |
| Long-tail pairs where LVR drives churn  | `lvr-aware` ✓     |
| Plain volatile majors (USDC/ETH)        | `simple-jit`      |

`simple-jit` fills any profitable intent. `lvr-aware` only fills when the JIT cycle **reduces** LP loss-versus-rebalancing — i.e., when the swap moves price *toward* external consensus, not away from it. This means smaller volume, but pools you operate retain LP capital longer.

## How LVR is computed (v0)

For a swap of size `X`, current pool liquidity `L`, implied vol `σ`:

```
LVR ≈ X² × σ² / (8 × L)
```

The JIT fill reduces LVR proportional to its liquidity contribution:

```
reduction ≈ LVR × (Δliquidity / (L + Δliquidity))
```

We only submit when `reduction > 0` AND net solver profit (after intended donation) meets `MIN_PROFIT_USD`. See [`src/lvr.ts`](./src/lvr.ts) for the full math + simplification caveats.

**Plug an oracle for production**: v0 uses static `VOLATILITY_BPS` from `.env`. Wire Pyth's realised-vol feed (or similar) in `strategy.ts:decide` for production accuracy.

## On-chain donation gap

The plan was to **donate 25% of fees** back to passive LPs via `PoolManager.donate(poolKey, amount0, amount1, hookData)`. v4 enforces `donate()` is `onlyByLocker` — must be called inside an `unlock()` callback. **An EOA writeContract call to `donate()` REVERTS.**

The proper donate path requires extending `Filler.sol` (Sprint 01) to call `donate()` inside `reactorCallback` (which is already inside the unlock context per the Reactor architecture). This is a contract change, out of v0 (template-only) scope.

**v0 ships filter-side LVR-favourable fills + emits `intended_donation_total_wei` metric** so you can see how much you'd donate if the on-chain path existed. When Sprint 01 ships the contract extension, the strategy flips one line to enable real donation.

## Quickstart

```bash
# 1. Configure
cp .env.example .env
# Edit .env — solver identity, RPC, addresses, VOLATILITY_BPS, BASE_LIQUIDITY_HINT.

# 2. Install
bun install

# 3. Stake bond (one-time)
bun stake                    # 0.1 ETH default

# 4. Run the solver
bun start

# 5. (Optional) View metrics
curl http://localhost:9090/metrics
curl http://localhost:9090/health
```

## Architecture (4 src files + 1 bond)

```
src/
├── config.ts     # Zod env loader (with VOLATILITY_BPS / BASE_LIQUIDITY_HINT)
├── lvr.ts        # Pure LVR math
├── strategy.ts   # filter() + async decide() with LVR analysis
├── filler.ts     # Main loop + Prometheus metrics endpoint
└── stake.ts      # One-time bond setup
```

## Metrics

`http://0.0.0.0:${METRICS_PORT}/metrics` (Prometheus format):

| Metric                            | Type    | What it tracks                                              |
| --------------------------------- | ------- | ----------------------------------------------------------- |
| `lvr_recaptured_total_wei`        | counter | Cumulative LVR reduction across submitted fills (input wei) |
| `intended_donation_total_wei`     | counter | What we'd donate to LPs once the contract path ships         |
| `fills_submitted_total{result}`   | counter | Fills attempted by outcome (success / strategy_rejected / submit_failed / prepare_failed / no_params) |
| `last_fill_block`                 | gauge   | Block number of the most recent successful fill             |

Plus Prometheus default process metrics (heap, CPU, event-loop lag).

## Customising

Edit `src/strategy.ts` — the LVR-aware logic lives there:

```ts
async decide(intent, params, minProfitWei, ctx) {
  // Plug an oracle for live volatility:
  ctx.volatilityBps = await fetchVolFromPyth(intent.input.token);

  // Only fill in low-vol windows (avoid high-LVR regimes):
  if (ctx.volatilityBps > 500) return { submit: false, ... };

  // Existing LVR check + profitability still applies.
  return /* ... */;
}
```

## Production deployment

1. Set `LOG_LEVEL=info`. Pipe stdout to your log aggregator (Datadog / Loki).
2. Scrape `:${METRICS_PORT}/metrics` from Prometheus. Alert on:
   - `rate(fills_submitted_total{result="success"}[5m])` falling to zero (solver dead).
   - `fills_submitted_total{result="strategy_rejected"}` ratio rising (LVR conditions no longer favourable — pool churn changed).
3. Run under systemd / pm2 / Docker for auto-restart.
4. Hold spare ETH in `SOLVER_PRIVATE_KEY` for gas + bond re-up.

## Documentation

- [Filler SDK reference](https://filler-sdk-docs.vercel.app)
- [Plan 04 progress doc](https://github.com/DavidZapataOh/filler-sdk/blob/main/plans/sprint-04-cli-references/04-lvr-aware-template-progress.md) — design rationale + on-chain-donate gap
- [Sprint 01 contract roadmap](https://github.com/DavidZapataOh/filler-sdk/tree/main/plans/sprint-01-smart-contracts) — when on-chain donate ships

## License

MIT
