# Generated by create-filler. Copy to `.env` and fill in.

# === REQUIRED ===

# Solver wallet private key — 0x-prefixed 32-byte hex.
# Anvil dev account #0 (BURN-IT, never send real funds):
#   0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
SOLVER_PRIVATE_KEY=

# RPC endpoint for {{chain}}.
# Must be https:// (http:// only allowed for localhost / 127.0.0.1).
RPC_URL={{rpcUrl}}

# === OPTIONAL ===

# JIT-hints indexer URL.
# Self-host via the @filler-sdk/jit-hints package for private depth queries.
INDEXER_URL={{indexerUrl}}

# Logging level: trace | debug | info | warn | error
LOG_LEVEL=info

# Minimum profit per fill in USD. Fills below this threshold are skipped.
MIN_PROFIT_USD=1{{#if useKeeperHub}}

# === KeeperHub (MEV-protected routing) ===

# Bearer token from KeeperHub onboarding.
KEEPERHUB_API_KEY=

# KeeperHub HTTP API base URL.
KEEPERHUB_BASE_URL=https://api.keeperhub.example.com{{/if}}
