/**
 * Extract the v4 PoolManager event ABI from the Foundry build artifact and emit a
 * type-safe `as const` TypeScript file at `abis/v4PoolManager.ts`.
 *
 * Source artifact: `contracts/out/IPoolManager.sol/IPoolManager.json`. We use the
 * INTERFACE artifact because (a) it has all the events we need (Initialize,
 * ModifyLiquidity, Swap, Donate, Transfer, Approval, OperatorSet) and (b) the
 * implementation contract is deployed by Uniswap, not us — building it locally
 * isn't necessary or useful.
 *
 * Usage: `bun run abi:gen` (after `cd contracts && forge build`).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, '..');
const REPO_ROOT = resolve(PKG_ROOT, '..', '..');

const SOURCES = [
  {
    artifact: resolve(
      REPO_ROOT,
      'contracts/out/IPoolManager.sol/IPoolManager.json',
    ),
    output: resolve(PKG_ROOT, 'abis/v4PoolManager.ts'),
    exportName: 'v4PoolManagerAbi',
    description: 'Uniswap v4 PoolManager interface ABI (events + functions).',
  },
];

interface AbiItem {
  type: string;
  name?: string;
  inputs?: unknown[];
  outputs?: unknown[];
  stateMutability?: string;
  anonymous?: boolean;
}

function generate(): void {
  for (const src of SOURCES) {
    if (!existsSync(src.artifact)) {
      console.error(
        `error: ${src.artifact} not found. Run \`cd contracts && forge build\` first.`,
      );
      process.exit(1);
    }

    const json = JSON.parse(readFileSync(src.artifact, 'utf-8')) as {
      abi: AbiItem[];
    };
    const abi = json.abi;
    if (!Array.isArray(abi) || abi.length === 0) {
      console.error(`error: artifact ${src.artifact} has no ABI`);
      process.exit(1);
    }

    const events = abi.filter((item) => item.type === 'event');
    if (events.length === 0) {
      console.error(`error: artifact ${src.artifact} contains no events`);
      process.exit(1);
    }

    const outDir = dirname(src.output);
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

    const file = `// This file is auto-generated by scripts/gen-abis.ts. Do not edit by hand.
// ${src.description}
// Regenerate with: bun run abi:gen

export const ${src.exportName} = ${JSON.stringify(abi, null, 2)} as const;
`;
    writeFileSync(src.output, file);
    console.log(
      `✓ ${src.output} (${abi.length} ABI items, ${events.length} events)`,
    );
  }
}

generate();
