/**
 * Auto-generate the SDK's `as const` ABI bindings from Foundry artifacts.
 *
 * The Solidity contracts under `contracts/src/` are the canonical source of
 * truth for the on-chain interface; this script extracts the ABI fragments
 * the SDK needs and emits them as TypeScript `as const` arrays. Solver authors
 * (and the SDK itself) consume these via `import { fillerAbi } from '@filler-sdk/sdk/abis'`,
 * which lets viem narrow argument + return types per-function at compile time.
 *
 * Why generate vs. hand-write:
 *   - Hand-written ABIs drift the moment a contract changes.
 *   - Pulling them from artifacts means `forge build` is the single source of
 *     truth — no subtle copy-paste bugs.
 *   - Foundry already produces machine-readable JSON; the cost is one script.
 *
 * Usage:  `bun run abi:gen` (after `cd contracts && forge build`)
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, '..');
const REPO_ROOT = resolve(PKG_ROOT, '..', '..');

interface AbiSource {
  artifact: string;
  output: string;
  exportName: string;
  description: string;
}

const SOURCES: readonly AbiSource[] = [
  {
    artifact: resolve(REPO_ROOT, 'contracts/out/Filler.sol/Filler.json'),
    output: resolve(PKG_ROOT, 'src/abis/filler.ts'),
    exportName: 'fillerAbi',
    description: 'Filler executor — entrypoint for atomic JIT fills.',
  },
  {
    artifact: resolve(REPO_ROOT, 'contracts/out/FillerBond.sol/FillerBond.json'),
    output: resolve(PKG_ROOT, 'src/abis/fillerBond.ts'),
    exportName: 'fillerBondAbi',
    description: 'FillerBond — slashable bond contract for solver accountability.',
  },
  {
    artifact: resolve(
      REPO_ROOT,
      'contracts/out/IPoolManager.sol/IPoolManager.json',
    ),
    output: resolve(PKG_ROOT, 'src/abis/poolManager.ts'),
    exportName: 'poolManagerAbi',
    description: 'Uniswap v4 PoolManager interface (events + functions).',
  },
];

interface AbiItem {
  type: string;
  name?: string;
  inputs?: unknown[];
  outputs?: unknown[];
  stateMutability?: string;
  anonymous?: boolean;
}

function generate(): void {
  for (const src of SOURCES) {
    if (!existsSync(src.artifact)) {
      console.error(
        `error: ${src.artifact} not found. Run \`cd contracts && forge build\` first.`,
      );
      process.exit(1);
    }

    const json = JSON.parse(readFileSync(src.artifact, 'utf-8')) as {
      abi: AbiItem[];
    };
    const abi = json.abi;
    if (!Array.isArray(abi) || abi.length === 0) {
      console.error(`error: artifact ${src.artifact} has no ABI`);
      process.exit(1);
    }

    const outDir = dirname(src.output);
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

    const events = abi.filter((item) => item.type === 'event').length;
    const fns = abi.filter((item) => item.type === 'function').length;

    const file = `// This file is auto-generated by scripts/gen-abis.ts. Do not edit by hand.
// ${src.description}
// Regenerate with: bun run abi:gen

export const ${src.exportName} = ${JSON.stringify(abi, null, 2)} as const;
`;
    writeFileSync(src.output, file);
    console.log(
      `✓ ${src.output.replace(`${REPO_ROOT}/`, '')} (${abi.length} items, ${events} events, ${fns} fns)`,
    );
  }
}

generate();
