# Generated by create-filler (treasury-rebalance vertical). Copy to `.env` and fill in.
#
# Treasury-rebalance ships with TWO modes — see DEMO_MODE below.

# === DEMO MODE — fastest path to a live "spread captured" counter ===

# When true, the solver uses createMockFiller from @filler-sdk/sdk/testing
# + emits synthetic intents from `TREASURY_ADDRESS`. No chain access; no bond
# required; no SOLVER_PRIVATE_KEY needed. Useful for hackathon demos +
# local development without RPC / Reactor / PoolManager deployment.
DEMO_MODE=true

# Demo intent generation interval (seconds). Default 10.
DEMO_INTERVAL_SEC=10

# === REQUIRED — DAO treasury identity ===

# DAO treasury Safe address. In demo mode, synthetic intents are emitted
# from this address so `strategy.filter` accepts them.
TREASURY_ADDRESS=0x0000000000000000000000000000000000000007

# Rebalance schedule: weekly | monthly | quarterly. v0 informational.
REBALANCE_SCHEDULE=quarterly

# Target allocation as a JSON string of TICKER→percentage. Sum = 100.
# Example: AAVE-style 60/40 ETH/USDC.
TARGET_ALLOCATIONS={"ETH":60,"USDC":40}

# Token addresses for THIS chain as a JSON string of TICKER→0x-address.
# Demo mode uses these to pick random pairs for synthetic intents.
# Example for Unichain mainnet:
TOKEN_ADDRESSES={"ETH":"0x4200000000000000000000000000000000000006","USDC":"0x078d782b760474a361dda0af3839290b0ef57ad6","DAI":"0x20cab320a855b39f724131c69424240519573f81"}

# Minimum rebalance amount in USD that triggers a fill. Smaller intents skip.
MIN_REBALANCE_USD=10000

# === Dashboard SSE endpoint ===

# Port for the dashboard SSE server. Sprint 05's money counter
# subscribes to `http://localhost:${DASHBOARD_PORT}/events`.
DASHBOARD_PORT=8080

# === PRODUCTION MODE — only required when DEMO_MODE=false ===

# Solver wallet — only needed in production. In demo mode, the mock filler
# uses anvil[0] internally + never broadcasts.
# Anvil dev account #0 (DEMO ONLY — never send real funds):
#   0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
SOLVER_PRIVATE_KEY=

# Chain id (you scaffolded for `{{chain}}`).
# Supported: 1 mainnet | 130 unichain | 8453 base | 42161 arbitrum | 10 optimism
#            11155111 sepolia | 11155420 unichain-sepolia | 31337 foundry
CHAIN_ID=130

# RPC endpoint — must be https:// (http:// only allowed for localhost).
RPC_URL={{rpcUrl}}

# Deployed contracts on {{chain}}.
FILLER_ADDRESS=
BOND_ADDRESS=
REACTOR_ADDRESS=
POOL_MANAGER_ADDRESS=

# JIT-hints indexer URL.
INDEXER_URL={{indexerUrl}}

# Logging level: trace | debug | info | warn | error | fatal
LOG_LEVEL=info{{#if useKeeperHub}}

# === KeeperHub (MEV-protected routing) ===

KEEPERHUB_API_KEY=
KEEPERHUB_BASE_URL=https://api.keeperhub.example.com{{/if}}
